### PR TITLE
feat(gcs):change signature to s3v2 based on gcs domain

### PR DESCRIPTION
**Pull request by smothiki**
add support for gCS

### CODE REVIEW

**Comment by smothiki** [comment]
closes https://github.com/deis/slugrunner/issues/17

**Comment by arschles** [comment]
@smothiki when this is ready for review, can you please add some testing instructions and replace the `in progress` label with `awaiting review`?

**Comment by smothiki** [comment]
Testing instructions 
- use the following images smothiki/workflow:v1.6 and smothiki/builder:v1.3 for workflow and builder.
- turn on interoperabiltiy mode GCS storage.
- change credentials in deis-minio-secret-user
- set the below env variables in builder RC

```
            - name: "DEIS_OUTSIDE_STORAGE"
              value: "storage.googleapis.com"
            - name: "BUCKET"
              value: "<what ever unique bucket>"
```

**Comment by bacongobbler** [comment]
did not manually test, but code LGTM.

**Comment by arschles** [comment]
@smothiki I've removed the `in progress` label, and I'll test shortly

**Comment by bacongobbler** [comment]
manually tested and verified:

```
$ ls tmp/
access-key-id  access-secret-key
$ docker run -v $PWD/tmp:/var/run/secrets/object/store -e SLUG_URL=https://storage.googleapis.com/foo -e DEBUG=1  192.168.0.20:5000/deis/slugrunner:0.0.1-20160308125029
+ export HOME=/app
+ HOME=/app
+ mkdir -p /app
+ gcs=storage.googleapis.com
++ ls -A /app
+ [[ -n '' ]]
+ [[ -n https://storage.googleapis.com/foo ]]
+ [[ -e /var/run/secrets/object/store/access-key-id ]]
+ [[ -e /var/run/secrets/object/store/access-secret-key ]]
++ cat /var/run/secrets/object/store/access-key-id
+ keyID=foo
++ cat /var/run/secrets/object/store/access-secret-key
+ secretKey=bar
++ echo https://storage.googleapis.com/foo
++ awk -F/ '{print $1}'
+ protocol=https:
++ echo https://storage.googleapis.com/foo
++ awk -F/ '{print $3}'
+ domain=storage.googleapis.com
+ '[' storage.googleapis.com = storage.googleapis.com ']'
+ mc config host add https://storage.googleapis.com foo bar S3v2

$ docker run -v $PWD/tmp:/var/run/secrets/object/store -e SLUG_URL=https://foo.example.com/foo -e DEBUG=1  192.168.0.20:5000/deis/slugrunner:0.0.1-20160308125029
+ export HOME=/app
+ HOME=/app
+ mkdir -p /app
+ gcs=storage.googleapis.com
++ ls -A /app
+ [[ -n '' ]]
+ [[ -n https://foo.example.com/foo ]]
+ [[ -e /var/run/secrets/object/store/access-key-id ]]
+ [[ -e /var/run/secrets/object/store/access-secret-key ]]
++ cat /var/run/secrets/object/store/access-key-id
+ keyID=foo
++ cat /var/run/secrets/object/store/access-secret-key
+ secretKey=bar
++ echo https://foo.example.com/foo
++ awk -F/ '{print $1}'
+ protocol=https:
++ echo https://foo.example.com/foo
++ awk -F/ '{print $3}'
+ domain=foo.example.com
+ '[' foo.example.com = storage.googleapis.com ']'
+ mc config host add https://foo.example.com foo bar
```

**Pull request merged**
